[package]
name = "try_fold_impl"
version = "0.1.2"
edition = "2021"
description = "Simple macro for deriving Iterator::next and ::fold from a ::try_fold implementation"
license = "MIT"

[dependencies]
